# Generated by Django 5.0.6 on 2024-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("taste", models.CharField(max_length=124)),
                ("color", models.CharField(max_length=124)),
                ("price", models.FloatField()),
            ],
        ),
    ]
